### PR TITLE
fix TypeError: fclose(): supplied resource is not a valid stream reso…

### PR DESCRIPTION
**Pull request by remicollet**

### CODE REVIEW

**Comment by glensc** [comment]
FYI, in zf1s https://github.com/zf1s/zf1/pull/32 handled as 

```diff
diff --git a/packages/zend-mail/library/Zend/Mail/Storage/Mbox.php b/packages/zend-mail/library/Zend/Mail/Storage/Mbox.php
index 90e3791c..de963804 100644
--- a/packages/zend-mail/library/Zend/Mail/Storage/Mbox.php
+++ b/packages/zend-mail/library/Zend/Mail/Storage/Mbox.php
@@ -335,7 +335,9 @@ class Zend_Mail_Storage_Mbox extends Zend_Mail_Storage_Abstract
      */
     public function close()
     {
-        @fclose($this->_fh);
+        if ($this->_fh && 'Unknown' !== get_resource_type($this->_fh)) {
+            @fclose($this->_fh);
+        }
         $this->_positions = array();
     }

```

**Comment by remicollet** [comment]
@glensc sorry, don't understand your comment

**Comment by remicollet** [comment]
Notice there is also tons of `Warning: Undefined array key 1 ...` related to bad explode usage in various place

**Comment by remicollet** [comment]
I really think this component is NOT yet compatible with PHP 8

**Comment by glensc** [comment]
> @glensc sorry, don't understand your comment

my [comment](https://github.com/laminas/laminas-mail/pull/134#issuecomment-767680909) is informative, take or leave it. `FYI` stands for `For Your Information`.

**Comment by glensc** [comment]
> I really think this component is NOT yet compatible with PHP 8

You should set your PR status to Draft while it's not ready for merge.

**Comment by remicollet** [comment]
It is ready to merge as it fixes the test suite.

Remaining warnings have to be fixed, but out of the scope of this issue

**Comment by Ocramius** [comment]
> I really think this component is NOT yet compatible with PHP 8

Can't do much about that besides pursuing further issues, like #113 :-\

I see that travis-ci completely abandoned us today :-(

**Comment by glensc** [comment]
yes, travis gone already yesterday:
- https://github.com/laminas/laminas-mail/issues/133

**Pull request merged**
