### PR TITLE
Mark package as abandoned

### PR DESCRIPTION
**Pull request by PEyacher**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description
TIL that this package has been discontinued in December of last year (thanks to the comment of @arhimede on my recent [pull request](https://github.com/laminas/laminas-mail/pull/266)). Apart from the [maintenance status page on the laminas website](https://getlaminas.org/packages-maintenance-status/) there is no indication of this to be found whatsoever. I hereby provide a pull request with the changes that have been decided at the TSC Meeting on December 4th 2023 as [documented here](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2023-12-04-TSC-Minutes.md#decision). I provide this change with the intention, that people can know that they are using a package that has been discontinued and what replacement options have been recommended.

### CODE REVIEW

**Comment by froschdesign** [comment]
@PEyacher 
This package is not _abandoned_ and therefore all changes are unnecessary.

The readme file should contain the following:

```markdown
> ## Security-Only Maintenance Mode
> 
> This package is considered feature-complete, and is now in **security-only** maintenance mode, following a [decision by the Technical Steering Committee](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2023-12-04-TSC-Minutes.md#decision).
> If you have a security issue, please [follow our security reporting guidelines](https://getlaminas.org/security/).
> If you wish to take on the role of maintainer, please [nominate yourself](https://github.com/laminas/technical-steering-committee/issues/new?assignees=&labels=Nomination&template=Maintainer_Nomination.md&title=%5BNOMINATION%5D%5BMAINTAINER%5D%3A+%7Bname+of+person+being+nominated%7D)
```

**Comment by PEyacher** [comment]
Hi @froschdesign 

All public information I could find indicates that the project is discontinued/abandoned. This includes 
- The ["Current Maintenance Status of Laminas & Mezzio Packages" page on the laminas website](https://getlaminas.org/packages-maintenance-status/) where this package is tagged with the "discontinued" and not the "security-only" badge: 
image
- The [minutes of the TSC meeting on 2023-12-04](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2023-12-04-TSC-Minutes.md#decision) where the following is stated:
> **Decision**
> We will abandon laminas-mail and laminas-mime. We will add recommendations to the three other projects in the README, and link to symfony/mailer for the "abandoned" property of the project.

Can you confirm that the information from these sources is incorrect/outdated?

**Comment by froschdesign** [comment]
@PEyacher 
I am confused because the repository is still open and but the package is abandoned. 🤦🏻 🤷🏻‍♂️

**Comment by Slamdunk** [comment]
Sorry, I thought that putting packages on maintenance mode was up to the TSC, but apparently I can take this responsability myself.

**Review by Slamdunk — APPROVED** [review]

**Comment by Slamdunk** [comment]
@weierophinney can you push this button on the linked page please?

https://github.com/laminas/laminas-mail/settings
image

**Pull request merged**
