### PR TITLE
[2.14]: QA: Add specific type hints for $params

### PR DESCRIPTION
**Pull request by glensc**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Extracted from https://github.com/laminas/laminas-mail/pull/109

These need line length exception, which is difficult to setup, hence the separate PR to be able to work on the specific problem only.

### CODE REVIEW

**Comment by glensc** [comment]
I just realized I could change `Protocol\Pop3` -> `Pop3` in import to save some bytes. This reduces code readability but "solves" the problem.

**Comment by glensc** [comment]
aside, why "coverage/coveralls — Coverage remained the same at 62.166%" is an error? coverage **must** increase with each PR? :)

**Comment by Ocramius** [comment]
Really don't know about the coveralls setup: I can imagine it erroring due to floating point comparisons.

**Review by Ocramius — APPROVED** [review]
LGTM

**Comment by glensc** [comment]
> LGTM

@Ocramius this can't be merged until Travis is fixed. It will continue to haunt all future PR's. The check runs on all code, not just modified lines.

I created the PR, so getting the ignore rules to work can be experimented, as I failed to find anything working in https://github.com/laminas/laminas-mail/pull/109 (details in notes in there), and I understood you also tried something but failed as well.

**Comment by Ocramius** [comment]
Probably better to merge #127 first then

**Comment by glensc** [comment]
@Ocramius what exactly from there? can you point to a commit?

**Comment by Ocramius** [comment]
@glensc since #127 and #117 are handled, could you run a rebase here, when you have time? In theory, that restores CI build status.

**Comment by glensc** [comment]
@Ocramius seems you lost context, the CI failure is due to CS:
- https://travis-ci.com/github/laminas/laminas-mail/jobs/470947398#L646

I created this PR out of https://github.com/laminas/laminas-mail/pull/109 due unable to handle "line length cs violation", as the chunks did not get any resolution (so it got excluded from #109) nor any help on the matter as outlined in the PR body.

Please see the discussion in https://github.com/laminas/laminas-mail/pull/109 it goes around the problem in rounds and rounds.

Here are direct links to each of the posts, but I find it easier to just read the whole PR notes top to bottom.
- https://github.com/laminas/laminas-mail/pull/109#issuecomment-677457638
- https://github.com/laminas/laminas-mail/pull/109#issuecomment-752932424
- https://github.com/laminas/laminas-mail/pull/109#issuecomment-752935255
- https://github.com/laminas/laminas-mail/pull/109#issuecomment-753326833
- https://github.com/laminas/laminas-mail/pull/109#issuecomment-755361506
- https://github.com/laminas/laminas-mail/pull/109#issuecomment-755365671
- https://github.com/laminas/laminas-mail/pull/109#issuecomment-757676676
- https://github.com/laminas/laminas-mail/pull/109#issuecomment-758847142

For this PR to go forward, need help with how to set up the CS violation exclude.

**Comment by Ocramius** [comment]
Let's disable the CS rule overall then: see example at https://github.com/Ocramius/ProxyManager/blob/c078f63a4224c518f3e007ad1d8b774fdcf38b70/phpcs.xml.dist#L20-L21

**Comment by glensc** [comment]
Hmm, can't find Travis integration at all anymore.

And seems already master broken with test/Transport/SendmailTest.php from #117:

```
FILE: /Users/glen/scm/php/zend-mail/test/Transport/SendmailTest.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
  97 | WARNING | Line exceeds 120 characters; contains 130 characters
 283 | WARNING | Line exceeds 120 characters; contains 122 characters
----------------------------------------------------------------------
```

Will send separate PR with CS fix disable

**Comment by glensc** [comment]
@Ocramius your suggestion is too complex, what to put under the name "Doctrine"?
Using value "Doctrine" obviously is not wanted, as that will enable ruleset named "Doctrine".

This project does include to `vendor/laminas/laminas-coding-standard/ruleset.xml` which has `name="Zend Framework Coding Standard"`, using that results in a fatal error of ruleset not found. 

anyway, found this page:
- https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#genericfileslinelength


Property Name | Type | Default | Available Since
-- | -- | -- | --
lineLimit | int | 80 | -
absoluteLineLimit | int | 100 | -
ignoreComments | bool | false | 3.1.0

what values to set here?

**Comment by glensc** [comment]
Submitted PR to up the limits: https://github.com/laminas/laminas-mail/pull/132

**Comment by froschdesign** [comment]
@glensc 
Based on your [comment](https://github.com/laminas/laminas-mail/pull/109#issuecomment-755365671):

> The phpcs:disable has no effect…

and the old PHP_CodeSniffer version, I think that the use is wrong. Try the old syntax:

```php
// @codingStandardsIgnoreStart
protected function _detectCallbackUrl()
{
    // @codingStandardsIgnoreEnd
}
```

([laminas-coding-standard 1.0.0 uses version 2](https://github.com/laminas/laminas-coding-standard/blob/08880ce2fbfe62d471cd3cb766a91da630b32539/composer.json#L23) of PHP_CodeSniffer but the new comments were added in version [3.2.0](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.2.0).)

**Comment by glensc** [comment]
@froschdesign ok. that makes a lot of sense! thanks for figuring that out.

but, what now?
1. is there a plan for upgrading code standard in this project? 
2. just proceed with old syntax?
3. ignore the problem?
   - Travis is dead anyway: https://github.com/laminas/laminas-mail/issues/133
   - and master has more of these violations merged (from https://github.com/laminas/laminas-mail/pull/117) as the cs was not checked due reason above.

**Comment by glensc** [comment]
CI green now

**Pull request merged**
