### PR TITLE
Fixes #13 : use instanceOf property in SmtpPluginManager for exception message

### LINKED ISSUE #13: Code style improvements
See individual commit messages for details.

---

Originally posted by @glensc at https://github.com/zendframework/zend-mail/pull/231

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Re-create https://github.com/zendframework/zend-mail/pull/231 by @glensc Fixes #13

### CODE REVIEW

**Comment by glensc** [comment]
@samsonasik please preserve authorship of original commit. using `git commit --amend --author` for example. or just `git fetch REPO_URL && git cherry-pick COMMIT`, `wget https://github.com/zendframework/zend-mail/pull/231.patch && git am 231.patch` works as well.

**Comment by samsonasik** [comment]
@glensc You can create separate PR instead, and I will close this PR

**Comment by glensc** [comment]
@samsonasik this applies to all PR's you carry over. so it's beneficial for you to learn how to do do this.

**Comment by samsonasik** [comment]
I always mention the original author in the PR description, if original author want to use their own commit, they can create separate PR instead, and I will close the PR immediately.

**Comment by samsonasik** [comment]
I know about cherry pick, rebase and their friends, and mostly that create conflict for migrated code. That's I don't have enough time!

If You Want to use your own commit as original author, just create separate PR and I will close this.

**Comment by weierophinney** [comment]
I used the `wget` + `git am` technique from @glensc locally, and it merged without conflicts. I've now pushed that into the 2.12.x branch, making this PR obsolete.

**Comment by glensc** [comment]
@samsonasik PR body is not the same as git commit. I can use git without github.

**Pull request closed without merging**
