### PR TITLE
Remove file headers

### PR DESCRIPTION
**Pull request by ghostwriter**
**[QA]** Remove file header (DocBlock comments)

### CODE REVIEW

**Comment by glensc** [comment]
@ghostwriter why?

**Comment by glensc** [comment]
@ghostwriter this violates project licensing:
- https://github.com/laminas/laminas-mail/blob/2.14.0/LICENSE.md

> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

**Comment by Ocramius** [comment]
https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-12-07-TSC-Minutes.md#master-branch-references-and-license-docblocks

Headers are being dropped pretty much everywhere.

**Comment by ghostwriter** [comment]
> @ghostwriter why?

https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-12-07-TSC-Minutes.md#master-branch-references-and-license-docblocks

**Comment by ghostwriter** [comment]
@glensc It's on the TSC Agenda

> ...we have LICENSE and COPYRIGHT files in each repository, 
and since code is installed with these files, it's up to the distributor
of code to ensure that attribution is present...

> As such, we have decided to remove the DocBlocks from code files. [`more`](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-12-07-TSC-Minutes.md#master-branch-references-and-license-docblocks)

**Comment by Slamdunk** [comment]
Thanks @ghostwriter

**Pull request merged**
