### PR TITLE
Fix encoding in sendmail transport with php8 (based on 2.14.x)

### LINKED ISSUE #162: [BUG] [PHP8] "Sendmail" Transport - Mailencoding is broken after php core fixes
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.14.X + 2.15.X
| PHP |  >= 8.0

#### Summary

PHP Core fixed a bug in php ( https://bugs.php.net/bug.php?id=47983 ) which expectes mail content to contain CRLF line endings 

#### Current behavior

https://github.com/laminas/laminas-mail/blob/ee318f54ca9d9d475acfea074e8077e56c5198bc/src/Transport/Sendmail.php#L123-L128

Line endings are filtered

more infos on topic: https://github.com/PHPMailer/PHPMailer/pull/2188

#### How to reproduce

Send an HTML email with `sendmail` transport with PHP 7 and PHP 8 and see the PHP 8 versions is broken because it can't be parsed and is detected as `Content-Type: text/plain`

#### Expected behavior

https://github.com/laminas/laminas-mail/blob/ee318f54ca9d9d475acfea074e8077e56c5198bc/src/Transport/Sendmail.php#L123-L128

don't replace `"\r\n"` with `"\n"`

#### Fix:

remove the replaces (PR is #164  )

### PR DESCRIPTION
**Pull request by Fahl-Design**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | yes
| QA            | yes

### Description

new PR based on `2.14.x` because of bugfix

fixes #162 and replace PR #163

### CODE REVIEW

**Comment by Fahl-Design** [comment]
Hi @Slamdunk i changed the base and fixed an other pslam error, but psalm still fails in github actions with an unrelated error

I can't reproduce it local on php 7.4 or 8.0 but I will try to reproduce it with 7.3 later today

from https://github.com/laminas/laminas-mail/pull/164/checks?check_run_id=3369753808
```
Running ./vendor/bin/psalm --shepherd --stats --output-format=github --no-cache
Scanning files...
PHP Fatal error:  Trait 'Laminas\Db\Adapter\AdapterAwareTrait' not found in /github/workspace/vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 27
Fatal error: Trait 'Laminas\Db\Adapter\AdapterAwareTrait' not found in /github/workspace/vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 27```

**Comment by Fahl-Design** [comment]
> Hi @Slamdunk i changed the base and fixed an other pslam error, but psalm still fails in github actions with an unrelated error
> 
> I can't reproduce it local on php 7.4 or 8.0 but I will try to reproduce it with 7.3 later today
> 
> from https://github.com/laminas/laminas-mail/pull/164/checks?check_run_id=3369753808
> 
> ```
> Running ./vendor/bin/psalm --shepherd --stats --output-format=github --no-cache
> Scanning files...
> PHP Fatal error:  Trait 'Laminas\Db\Adapter\AdapterAwareTrait' not found in /github/workspace/vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 27
> Fatal error: Trait 'Laminas\Db\Adapter\AdapterAwareTrait' not found in /github/workspace/vendor/laminas/laminas-validator/src/Db/AbstractDb.php on line 27```
> ```

Well.. I found the issue, and it's a little rabbit hole,

psalm fails because missing `laminas/laminas-db` in `laminas/laminas-validator` "require" section, when I try to run composer up in `laminas-validator` it fails because `laminas/laminas-http` needs `laminas/laminas-validator`

to simulate a fix I added `laminas/laminas-db` as dev package to `laminas-mail`  which results in psalm scanning more files and trigger even more errors:

``` 
::error file=src/Header/ContentTransferEncoding.php,line=96,col=54::Argument 2 of implode expects array<array-key, null|object{__tostring()}|scalar>, parent type array<array-key, mixed> provided (see https://psalm.dev/194)
::error file=src/Header/GenericMultiHeader.php,line=53,col=44::Argument 2 of implode expects array<array-key, null|object{__tostring()}|scalar>, parent type array{0: mixed|string}<int, mixed|string> provided (see https://psalm.dev/194)
::error file=src/Headers.php,line=530,col=27::$item is never referenced or the value is not used (see https://psalm.dev/275)
::error file=src/Protocol/AbstractProtocol.php,line=92,col=64::Argument 2 of implode expects array<array-key, null|object{__tostring()}|scalar>, parent type array<array-key, mixed> provided (see https://psalm.dev/194)
::error file=src/Protocol/AbstractProtocol.php,line=163,col=28::Argument 2 of implode expects array<array-key, null|object{__tostring()}|scalar>, parent type array<array-key, mixed> provided (see https://psalm.dev/194)
::error file=src/Protocol/AbstractProtocol.php,line=304,col=21::Calling empty on a boolean value is almost certainly unintended (see https://psalm.dev/004)
::error file=src/Protocol/Imap.php,line=395,col=35::Argument 2 of implode expects array<array-key, null|object{__tostring()}|scalar>, parent type list<mixed|string> provided (see https://psalm.dev/194)
::error file=src/Protocol/Imap.php,line=535,col=33::Argument 2 of implode expects array<array-key, null|object{__tostring()}|scalar>, parent type array<array-key, mixed> provided (see https://psalm.dev/194)
::error file=src/Protocol/Smtp.php,line=279,col=64::Argument 2 of implode expects array<array-key, null|object{__tostring()}|scalar>, parent type array<array-key, mixed> provided (see https://psalm.dev/194)
::error file=src/Protocol/SmtpPluginManager.php,line=85,col=30::Argument 1 of Laminas\Mail\Protocol\SmtpPluginManager::validate has wrong name $plugin, expecting $instance as defined by Laminas\ServiceManager\PluginManagerInterface::validate (see https://psalm.dev/230)
::error file=src/Storage/Maildir.php,line=71,col=41::$v is never referenced or the value is not used (see https://psalm.dev/275)
::error file=src/Storage/Writable/Maildir.php,line=672,col=9::Cannot access value on variable $filedata['flags'] using offset value of 'flags', expecting int (see https://psalm.dev/115)
::error file=src/Storage/Writable/Maildir.php,line=673,col=9::Cannot access value on variable $filedata['filename'] using offset value of 'filename', expecting int (see https://psalm.dev/115)
::error file=test/HeadersTest.php,line=46,col=23::Constructor PHPUnit\Framework\Error\Error::__construct is internal to PHPUnit but called from LaminasTest\Mail (see https://psalm.dev/175)
::error file=test/Storage/ImapTest.php,line=706,col=34::$message is never referenced or the value is not used (see https://psalm.dev/275)
::error file=test/Storage/MboxInterfaceTest.php,line=72,col=35::$message is never referenced or the value is not used (see https://psalm.dev/275)
::error file=test/Storage/MboxInterfaceTest.php,line=96,col=35::$message is never referenced or the value is not used (see https://psalm.dev/275)
::error file=test/Storage/MboxInterfaceTest.php,line=108,col=61::$message is never referenced or the value is not used (see https://psalm.dev/275)
::error file=test/Storage/MboxInterfaceTest.php,line=120,col=61::$message is never referenced or the value is not used (see https://psalm.dev/275)

``` 

maybe it's needed to add more QA Steps like "composer-require-checker" ( https://github.com/maglnet/ComposerRequireChecker ) which will fail wenn you use code from a package not defined in `composer.json` (I fixed an other issue in https://github.com/laminas/laminas-hydrator/pull/64 for almost the same reason)
```
   ~/dev/php/github/laminas-mail    fix_encoding…ort_with_php !3 ?1 ❯ composer-require-checker
ComposerRequireChecker 3.2.0@cd6c6b91ee3c065e60a35ca1a67becb0ae86dbb7
The following 16 unknown symbols were found:
+----------------------------------------------------------+--------------------+
| Unknown Symbol                                           | Guessed Dependency |
+----------------------------------------------------------+--------------------+
| ctype_digit                                              | ext-ctype          |
| imap_mime_header_decode                                  | ext-imap           |
| imap_utf8                                                | ext-imap           |
| Interop\Container\ContainerInterface                     |                    |
| Laminas\Crypt\Hmac                                       |                    |
| Laminas\ServiceManager\AbstractPluginManager             |                    |
| Laminas\ServiceManager\Exception\InvalidServiceException |                    |
| Laminas\ServiceManager\FactoryInterface                  |                    |
| Laminas\ServiceManager\Factory\InvokableFactory          |                    |
| Laminas\ServiceManager\ServiceLocatorInterface           |                    |
| Laminas\ServiceManager\ServiceManager                    |                    |
| Zend\Mail\Protocol\Smtp                                  |                    |
| Zend\Mail\Protocol\SmtpPluginManager                     |                    |
| Zend\Mail\Protocol\Smtp\Auth\Crammd5                     |                    |
| Zend\Mail\Protocol\Smtp\Auth\Login                       |                    |
| Zend\Mail\Protocol\Smtp\Auth\Plain                       |                    |
+----------------------------------------------------------+--------------------+
``` 


@Slamdunk maybe just merge this fix first, there is a lot of unrelated pain following

**Comment by froschdesign** [comment]
@Fahl-Design 
> psalm fails because missing `laminas/laminas-db` in `laminas/laminas-validator` "require" section

laminas-db is not required in laminas-validator because it is only used in two validators and therefore optional, like many other components.

```json
"suggest": {
    "laminas/laminas-db": "Laminas\\Db component, required by the (No)RecordExists validator",
    "laminas/laminas-filter": "Laminas\\Filter component, required by the Digits validator",
    "laminas/laminas-i18n": "Laminas\\I18n component to allow translation of validation error messages",
    "laminas/laminas-i18n-resources": "Translations of validator messages",
    "laminas/laminas-math": "Laminas\\Math component, required by the Csrf validator",
    "laminas/laminas-servicemanager": "Laminas\\ServiceManager component to allow using the ValidatorPluginManager and validator chains",
    "laminas/laminas-session": "Laminas\\Session component, ^2.8; required by the Csrf validator",
    "laminas/laminas-uri": "Laminas\\Uri component, required by the Uri and Sitemap\\Loc validators",
    "psr/http-message": "psr/http-message, required when validating PSR-7 UploadedFileInterface instances via the Upload and UploadFile validators"
},
```

https://github.com/laminas/laminas-validator/blob/0c38c7b539b5dbbcbe100bc508a663cdd57b3731/composer.json#L53-L63

**Comment by Fahl-Design** [comment]
Hi @Ocramius @weierophinney any other solutions than "it's only used a few times so it's optional" ?

**Comment by froschdesign** [comment]
@Fahl-Design 
> solutions than "it's only used a few times so it's optional" ?

This is not a solution, this is only a hint.

You can also use the "contributors" channel on Slack for direct contact. See: https://getlaminas.org/participate/

**Pull request merged**
