### PR TITLE
Add support for PHP 8.2

### PR DESCRIPTION
**Pull request by gsteel**
|    Q          |   A
|-------------- | ------
| New Feature   | yes

### CODE REVIEW

**Comment by Ocramius** [comment]
`idn_to_ascii` missing in the CI environment? :thinking:

**Comment by gsteel** [comment]
I think it's weirdness with symfony polyfills and the intl extension - can't reproduce the issue locally

**Comment by gsteel** [comment]
So CI removes the intl extension and the symfony polyfills don't have any types - hopefully the assertions and var annotations will cover it?

**Review by Ocramius — APPROVED** [review]
Solution to the type issue looks good, thanks @gsteel!

**Pull request merged**
