### PR TITLE
Adds error code to runtime exception and adds test for rejected recip…

### LINKED ISSUE #236: Pass SMTP server response code to Runtime Exception
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    |no

#### Summary

It would be quite useful to pass the response code to the Exception in 

\Laminas\Mail\Protocol\AbstractProtocol::_expect

Would be pretty easy:
```php
diff --git a/src/Protocol/AbstractProtocol.php b/src/Protocol/AbstractProtocol.php
--- a/src/Protocol/AbstractProtocol.php	
+++ b/src/Protocol/AbstractProtocol.php
@@ -352,7 +352,7 @@
         } while (str_starts_with($more, '-'));
 
         if ($errMsg !== '') {
-            throw new Exception\RuntimeException($errMsg);
+            throw new Exception\RuntimeException($errMsg, $cmd);
         }
 
         return $msg;
```

### PR DESCRIPTION
**Pull request by schnumsel**
This is the requested PR to issue #236

### CODE REVIEW

**Comment by schnumsel** [comment]
Well, I corrected all the checks I understood but the 2 failing are **very** unclear to me. The two failing tests state:
```
Running ./vendor/bin/phpunit
PHP Fatal error:  Cannot make static method Laminas\ServiceManager\Test\CommonPluginManagerTrait::getPluginManager() non static in class LaminasTest\Mail\Protocol\SmtpPluginManagerCompatibilityTest in /github/workspace/test/Protocol/SmtpPluginManagerCompatibilityTest.php on line 16

Fatal error: Cannot make static method Laminas\ServiceManager\Test\CommonPluginManagerTrait::getPluginManager() non static in class LaminasTest\Mail\Protocol\SmtpPluginManagerCompatibilityTest in /github/workspace/test/Protocol/SmtpPluginManagerCompatibilityTest.php on line 16
```
but neither is `Laminas\ServiceManager\Test\CommonPluginManagerTrait::getPluginManager()` static:

```
    /**
     * Returns the plugin manager to test
     *
     * @return AbstractPluginManager
     */
    abstract protected function getPluginManager();
```
nor did I change anything in the `LaminasTest\Mail\Protocol\SmtpPluginManagerCompatibilityTest` class.    

Quite confused, maybe a wrong test?

Best regards,
Willi

**Comment by Ocramius** [comment]
Failure seems indeed unrelated to your changes 🤔

**Comment by gsteel** [comment]
This is a [BC break in ServiceManager 3.21](https://github.com/laminas/laminas-servicemanager/pull/184/files#diff-5470c7fee9ea3d84104b00ba271bfd93257384018f64b1a57e8105fc8b06ea2d)

Dropping support for PHP 8.0, bumping ServiceManager to ^3.21 and making the relevant method static here will 'fix' it, alternatively a conflict with 3.21 of SM ??

**Comment by Ocramius** [comment]
IMO just bumping in a new PR

**Comment by schnumsel** [comment]
Ok, got it, laminas/laminas-service-manager got updated while I was writing my fix :)
I'll do a separate PR and Issue

**Comment by schnumsel** [comment]
Hi there, so I understand the problems. I was trying to solve it, but now I am giving up, see 
[other PR #238](https://github.com/laminas/laminas-mail/pull/238). I'll open an issue about the case, because the test configuration and how to deal with 

> This is a [BC break in ServiceManager 3.21](https://github.com/laminas/laminas-servicemanager/pull/184/files#diff-5470c7fee9ea3d84104b00ba271bfd93257384018f64b1a57e8105fc8b06ea2d)

are way over my knowledge concerning the project. I'll merge the corrected branch in mine, once the work is done and hopefully it will pass all tests then.

Best regards,

Willi

**Comment by Ocramius** [comment]
To be clear, not expecting you to fix it: the situation arises due to internal breakages.

Thanks for trying though!

**Comment by Slamdunk** [comment]
@schnumsel I've fixed the upstream branch in https://github.com/laminas/laminas-mail/pull/233

Can you rebase yours please?

**Comment by Ocramius** [comment]
@schnumsel you merged upstream via 87bf441a834150fc8d71dd34c02cf4cef7f9306c

@Slamdunk needs a rebase here :D

**Comment by wilfriedwolf** [comment]
@Slamdunk Thanks! @Ocramius not very familiar with these steps I should have done a force push, I'll try ...

**Comment by wilfriedwolf** [comment]
So this one goes without rebase.... I'll learn :)

**Review by Ocramius — COMMENTED** [review]
Looking good now! Giving @Slamdunk the say on the state of this patch :)

**Review by Slamdunk — APPROVED** [review]

**Comment by Slamdunk** [comment]
Thank you @schnumsel

**Pull request merged**
